/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 IPadPro.gltf -k -K -t -T s 
Files: IPadPro.gltf [57.09KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\iPad-Pro\IPadPro-transformed.glb [243.93KB] (-327%)
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/apple-ipad-pro-e5ffb3c80b2d4d6690249f8ee2bdafbe
Title: Apple iPad Pro
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    iPad_Pro_2020_Body_0: THREE.Mesh
    iPad_Pro_2020_screen_0: THREE.Mesh
    camera_module_glass_0: THREE.Mesh
    ['camera1_camera1(2)_0']: THREE.Mesh
    camera_module2001_Camera_Flash_0: THREE.Mesh
    camera_module2001_Mic_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    camera12: THREE.MeshStandardMaterial
    Camera_Flash: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
}

export default function IpadPro(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/iPad-Pro/IPadPro-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="iPad_Pro_2020_Body_0" geometry={nodes.iPad_Pro_2020_Body_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="iPad_Pro_2020_screen_0" geometry={nodes.iPad_Pro_2020_screen_0.geometry} material={materials.screen} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="camera_module_glass_0" geometry={nodes.camera_module_glass_0.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="camera1_camera1(2)_0" geometry={nodes['camera1_camera1(2)_0'].geometry} material={materials.camera12} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="camera_module2001_Camera_Flash_0" geometry={nodes.camera_module2001_Camera_Flash_0.geometry} material={materials.Camera_Flash} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="camera_module2001_Mic_0" geometry={nodes.camera_module2001_Mic_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/iPad-Pro/IPadPro-transformed.glb')
